package:
    name: fftw
    version: "3.3.4"

source:
    fn: fftw-3.3.4.tar.gz
    url: http://www.fftw.org/fftw-3.3.4.tar.gz
    md5: 2edab8c06b24feeb3b82bbb3ebf3e7b3

requirements:
  build:
    - mpich
    - system
    - chrpath

about:
  home: http://fftw.org
  license: GNU General Public License (GPL)
  summary: 'The fastest Fourier transform in the west.'
